ReNFT Azrael v1 and Sylvester v1 indexers + Graphql Servers
rumble-kong-league/ethereum-indexer pull request #7
Opened 2022-03-22 16:03 UTC by Bautista-Baiocchi-lora

2022-03-24 11:54 UTC, nazariyv commented on .gitignore
> +docker-compose.yml
I suggest we remove this line from .gitignore

2022-03-24 11:55 UTC, nazariyv commented on indexer/src/config.py
> +    def sylvester_v1(cls):
there is no need to call it sylvester_v1. Sylvester is the name for it. v2 will have a different name. So just `sylvester`

2022-03-24 11:56 UTC, nazariyv commented on indexer/src/config.py
> +        Returns instance of an sylvester v1
`Returns instance of a sylvester`

2022-03-24 11:56 UTC, nazariyv commented on indexer/src/config.py
> +        log_filename = "sylvester_v1.log"
let's remove the `v1` everywhere. It is implied in the name

2022-03-24 11:57 UTC, nazariyv commented on indexer/src/config.py
> +            _type_: instance of this class with the correct
This type should be the name of this dataclass

2022-03-24 11:58 UTC, nazariyv commented on indexer/src/config.py
> +        Returns instance of an azrael v1
let's remove the versions here, please

2022-03-24 11:58 UTC, nazariyv commented on indexer/src/config.py
> +            _type_: instance of this class with the correct
let's state that the type is this dataclass

2022-03-24 11:59 UTC, nazariyv commented on server/src/main.py
> +        """@inheritdoc IServer"""
For all the @inheritdoc above, let's be consistent and state which interface they are inheriting it from like here

2022-03-24 12:02 UTC, nazariyv commented on indexer/src/transform/covalent.py
> +                    raise NotImplementedError(f'Undecoded convalent param: {decoded_param["type"]}')
`covalent` you wrote `convalent`

2022-03-24 12:03 UTC, nazariyv commented on indexer/src/transform/main.py
> +    """@inheritdoc"""
ITransform

2022-03-24 12:03 UTC, nazariyv commented on indexer/src/transformers/azrael_v1/event.py
> +This class defines ALL events generated by the Azrael v1 contract.
let's change the name of this file `azrael` same goes for sylvester_v1

2022-03-24 12:04 UTC, nazariyv commented on indexer/src/transformers/azrael_v1/event.py
> +    LentEvent DTO
what's a DTO?

2022-03-24 12:07 UTC, nazariyv commented on indexer/src/transformers/azrael_v1/event.py
> +        _id = f"{event['tx_hash']}_{event['log_offset']}"
let's define a `staticmethod` function that returns the id. That way we can easily change it one place in the future and it will propagate to all the places where we use it.

```
@staticmethod
def get_id(tx_hash, log_offset):
    return f"..."
```

with types ofc. Also, the separator should be defined as a constant, and we should use it inside of the f string

`f"{...}{ID_SEPARATOR}{...}"`

2022-03-24 12:11 UTC, nazariyv commented on indexer/src/transformers/azrael_v1/event.py
> +    def from_covalent(cls, event: Any, decoded_params: List[Any]):
this is not an optimal way to instantiate. Ideally you either:

(i) supply raw response here and construct the dataclass from it
(ii) have separate arguments for each of the attributes of the dataclass. This is because you cannot guarantee that the user of this function will supply the arguments in the correct order. And if they do not, you will have a difficult to spot bugs.

`from_covalent` means we are taking covalent response and handle it. However the way it is dealt with here, it assumes there is something in between that will handle getting us the decoded params. I suggest we go with creating this event from a raw covalent response. We can have an instance of covalent in the constructor, and we can then use it to decode those raw responses right inside of this dataclass, instead of delegating it to someone else.

2022-03-24 12:12 UTC, nazariyv commented on indexer/src/transformers/azrael_v1/event.py
> +            decoded_params: (List[Any]): a list of decoded covalent event parameters. Order is important!
exactly what I mentioned before. Shouldn't be.

2022-03-24 14:16 UTC, Bautista-Baiocchi-lora commented on .gitignore
> +docker-compose.yml
renamed to `docker-bauti-compose.yml`

2022-03-24 14:32 UTC, Bautista-Baiocchi-lora commented on indexer/src/transformers/azrael_v1/event.py
> +    LentEvent DTO
Data Transfer Object

2022-03-24 19:10 UTC, Bautista-Baiocchi-lora commented on indexer/src/transformers/azrael_v1/event.py
> +    def from_covalent(cls, event: Any, decoded_params: List[Any]):
went with option (ii)

2022-03-27 13:47 UTC, nazariyv commented on indexer/src/config.py
> +            if key == k and hasattr(self,
Bauti, you need to install and use pre-commit. It would not allow for this formatting...

Self and one line and k on the next.

2022-03-27 14:34 UTC, nazariyv commented on indexer/src/config.py
> +            if key == k and hasattr(self,
I have added pylint and black as part of workflow. We won't be able to merge this PR unless those checks pass. Currently, they wouldn't.

2022-03-27 14:56 UTC, nazariyv commented on indexer/src/config.py
> +        you can know all of the on-chain emitted events. Using these events
A very general description. This description can be used for any transformer and indexer. Let's be a more specific here about what state we are interested in for sylvester.

2022-03-27 14:57 UTC, nazariyv commented on indexer/src/config.py
> +            (Config): instance of this Config class instantiated with the correct
this is peak tautology sentence lol

instance of instantiated. config and configs.

2022-03-27 14:57 UTC, nazariyv commented on indexer/src/config.py
> +        you can know all of the on-chain emitted events. Using these events
Same as above. Let's be specific about what azrael does.

2022-03-27 15:00 UTC, nazariyv commented on indexer/src/main.py
> +    # azrael is renft's v1 collateral solution
we can remove all these comments and addresses here, since we have the config class that takes care of it all

2022-03-27 15:01 UTC, nazariyv commented on indexer/src/transform/covalent.py
> -                # todo: other types
this is going to backfire on us in the future. This todo has to be here, because we aren't decoding other types. Let's 'undelete' this comment please

2022-03-27 15:02 UTC, nazariyv commented on indexer/src/transform/main.py
> +    def _get_events_of_interest(self) -> List[str]:
this is super weird. What's the point of having this function? This is literally `return self._config['events']` from below.

2022-03-27 15:02 UTC, nazariyv commented on indexer/src/transformers/azrael/event.py
> +This class defines ALL events generated by the azrael contract.
`emitted` by the azrael contract

2022-03-27 15:05 UTC, nazariyv commented on indexer/src/transformers/azrael/main.py
> +        self._collection_name = f"{address}-state"
in case we parse the address somehow in the future, we would store that parsed address as `self._address`. So it is a bit safer to use `self._address` here instead of the arg.

2022-03-27 15:05 UTC, nazariyv commented on indexer/src/transformers/azrael/main.py
> +        """_summary_
todo for doc

2022-03-27 15:09 UTC, nazariyv commented on indexer/src/transformers/azrael/main.py
> +            lending_id=int(decoded_params[0]),
this is not good. We should be pulling them via indices. If something changes in the decoding algo, these would be invalid. We need to return a decoded dataclass from covalent with attribute names for all of this. So it would look like

```python
event  = RentedEvent.create(
  lending_id=decoded_params.lending_id,
  renter_address=decoded_params.renter_address,
  ...
)
```

Also, making it the responsibility of the decoder to store all these attributes in a correct data type.

2022-03-27 15:10 UTC, nazariyv commented on indexer/src/transformers/azrael/util.py
> +    decimal = round(decimal * 10**-4 , 4)
I don't think we are supposed to be rounding here. We should be just cutting off the number at that precision (I think).

2022-03-27 15:11 UTC, nazariyv commented on indexer/src/transformers/example_rumble_kong_league/main.py
> +
black pre-commit would not allow this whitespace

2022-03-27 15:11 UTC, nazariyv commented on indexer/src/transformers/sylvester/main.py
> +        self._collection_name = f"{address}-state"
self._address

2022-03-27 15:12 UTC, nazariyv commented on indexer/src/transformers/sylvester/main.py
> +            renting_id=int(decoded_params[2]),
dataclass for decoded params with correct types

2022-03-27 15:12 UTC, nazariyv commented on indexer/src/transformers/sylvester/util.py
> +    decimal = round(decimal * 10**-4 , 4)
precision / rounding point here again

2022-03-27 15:13 UTC, nazariyv commented on server/src/azrael/event.py
> +            )
formatting

2022-03-27 15:53 UTC, nazariyv requested changes
conversations

2022-03-27 16:44 UTC, Bautista-Baiocchi-lora commented on indexer/src/config.py
> +            if key == k and hasattr(self,
hombrew installed and ran `pre-commit install`

2022-03-27 16:51 UTC, Bautista-Baiocchi-lora commented on indexer/src/config.py
> +            (Config): instance of this Config class instantiated with the correct
improved 😆

2022-03-27 17:45 UTC, Bautista-Baiocchi-lora commented on indexer/src/config.py
> +        you can know all of the on-chain emitted events. Using these events
went ahead and moved most of the explanation to respective transformer definitions.

2022-03-27 17:46 UTC, Bautista-Baiocchi-lora commented on indexer/src/main.py
> +    # azrael is renft's v1 collateral solution
removed.

2022-03-27 17:47 UTC, Bautista-Baiocchi-lora commented on indexer/src/transform/covalent.py
> -                # todo: other types
done.

2022-03-27 17:52 UTC, Bautista-Baiocchi-lora commented on indexer/src/transformers/azrael/main.py
> +        self._collection_name = f"{address}-state"
done for all transformers.

2022-03-27 18:02 UTC, Bautista-Baiocchi-lora commented on indexer/src/transformers/azrael/util.py
> +    decimal = round(decimal * 10**-4 , 4)
just ahead and removed the rounding just incase. It should not affect anything given the decimal is bounded between 0 and 9999

2022-03-29 12:57 UTC, merged